alunduil/zfs-replicate

zfs/replicate/compress/command.py, zfs/replicate/error.py, zfs/replicate/filesystem/create.py, zfs/replicate/filesystem/destroy.py, zfs/replicate/filesystem/list.py, zfs/replicate/snapshot/destroy.py, zfs/replicate/snapshot/list.py, zfs/replicate/snapshot/send.py
=> Add basic ZFSReplicateError.

setup.py
* Update pylint.
* Update coveralls.
* Add long_description to setup.py.
=> Release 1.1.2 (develop)

setup.py
* Update pytest, isort, hypothesis, and mypy.
* Add trivial generate test.
* Add a test of verbose invocation of main.
* Allow FileNotFoundError in main invoke test.
=> Release 1.1.4 (develop)

requirements.txt, setup.py
=> Release 1.1.5 (master)

setup.py
=> Release 1.1.5 (develop)

setup.py
=> Release 1.1.6 (develop)

setup.py
=> Release 1.1.6 (master)

requirements.txt, setup.py
=> Release 1.1.7 (master)

setup.py
=> Release 1.1.7 (develop)

setup.py
Seems I screwed up tag names in github and am off by one patch level.
This just catches the releases up so we can get back in sync.
=> Release 1.1.8 (develop)

setup.py
Seems I screwed up tag names in github and am off by one patch level.
This just catches the releases up so we can get back in sync.
=> Release 1.1.8 (master)

setup.py
* Update pytest-runner.
* Generalize the check for a missing /usr/bin/env.
=> Release 1.1.9 (develop)

requirements.txt, setup.py, zfs_test/replicate_test/cli_test/main_test.py
* Update pytest-runner.
* Generalize the check for a missing /usr/bin/env.
=> Release 1.1.9 (master)

setup.py
* Update coveralls
* Update pytest
* Update hypothesis
=> Release 1.1.10 (master)

setup.py
* Update coveralls
* Update pytest
* Update hypothesis
=> Release 1.1.10 (develop)

requirements.txt, setup.py
=> Release 1.1.11 (master)

setup.py
=> Release 1.1.11 (develop)

setup.py
=> Release 1.1.12 (develop)

requirements.txt, setup.py
=> Release 1.1.12 (master)

setup.py
=> Release 1.1.13 (develop)

requirements.txt, setup.py
=> Release 1.1.13 (master)

setup.py
* Update vulture.
* Update pylint
=> Release 1.1.14 (develop)

requirements.txt, setup.py
* Update vulture.
* Update pylint
=> Release 1.1.14 (master)

setup.cfg
* Ensure travis is configured for current Python versions.
* Add generate tests found in the Haskell experiment.
* Add readonly option to required permissions
* Change from pylint to flake8.
* Switch from Makefile to pre-commit.
* Update dependencies and tool versions.
* Use bash variables to show command usage
* Use the public name of hypothesis's SearchStrategy
=> Create release 1.2.0 (develop).

pyproject.toml
* Add pre-commit hooks.
* Simplified and correct direnv and nix-shell environment.
* Switch to poetry and update some versions.
=> Release 1.3.0 (develop)

.travis.yml
Im not sure what conditions are appropriate to deploy this now that I'm
using poetry, but hopefully these conditions will trigger correctly next
time.
=> Tweak travis deploy conditions.

pyproject.toml
* Cache poetry in GitHub workflows.
* Hold back mdformat version update.
* Drop python 3.6 support in this version.
* Ignore given type mismatches with travis.
* Remove glaring Any usage.
* Drop extraneous coding statements.
* Fix compress option to include off.
* Update pre-commit dependencies.
* Drop coding lines from all python files.
* poetry update
* Replace travis with GitHub actions.
* Update poetry and pre-commit dependency versions.
* Ensure black is set to 120 characters.
* Ensure pre-commit formatting is applied.
* Add override for pytest version bug.
* Update dependencies.
* Tweak travis deploy conditions.
=> 1.4.0 (develop)

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/python-checks.yml, .pre-commit-config.yaml, poetry.lock, poetry.toml, pyproject.toml, zfs/replicate/cli/click.py, zfs/replicate/cli/main.py, zfs/replicate/error.py
Setting up a different ephemeral development environment from Nix because I've switched from NixOS to ChromeOS for my daily driver.  As a result, I'll be updating the Nix configuration less and less but won't be removing it.
=> Add VSCode devcontainer configuration.

pyproject.toml
* Repository updates (i.e., scaffolding, templating)
* Removed python 3.6 support
* Updated dependency versions
* Added support for VS Code devcontainer
* Incorporate 1.4.0 changes that were not released
=> Create release 2.0.0

pyproject.toml
This is mostly version updates and housekeeping for correctness.  No functional
changes come in this release.
=> Bump version to 3.1.0.

CHANGELOG.md
This should make it easier to see if a revision is actually required for a user facing purpose rather than just version bumps.
=> Add changelog to track interface changes

zfs/replicate/compress/command.py
Fixes https://github.com/alunduil/zfs-replicate/issues/349
=> Replace `lz4c` with `lz4`

CHANGELOG.md, README.md, pyproject.toml
This includes an update to the CHANGELOG.md and README.md for #350.
=> Bump version to 4.0.0
